---
run_cfg:
  mlflow_server_uri: http://localhost:5000
  mlflow_experiment: debug
  mlflow_run: sample_run
  seed: 2137
  # If set, overrides num_epochs and runs for the specified number of steps.
  continue_training_from_checkpoint:
  max_epochs: 5
  early_stopping_patience: 3
  ds_path: tmp/librittsr_processed
  batch_size: 2
  save_checkpoints: true
  num_workers: 4
  train_val_split: 0.95

ds_cfg:
  load_prosody_features: true
  pitch_quantization_params: null
  energy_quantization_params: null
  scale_prosody_features: false
  use_phoneme_level_prosody_features: false
  load_context_embeddings: true

train_cfg:
  loss_weights:
    mel_loss: 1.0
    pitch_pred_loss: 1.0
    energy_pred_loss: 1.0
    duration_pred_loss: 1.0
  gradient_clip_val: 0.5
  accumulate_grad_batches: 4

optimizer_cfg:
  lr: 1e-3
  betas: [0.9, 0.98]
  eps: 1e-8
  weight_decay: 1e-5
  lr_scheduler_gamma: 0.98

model_cfg:
  encoder:
    hidden_size: 128
    phoneme_vocab_size: 74
    pos_tags_vocab_size: 37
    ling_stats_dim: 4
    input_bert_dim: 128
    n_att_blocks: 1
    conformer_kernel_size: 9
    att_feature_map_dim: 96
    num_att_heads: 4
    prenet_dropout_rate: 0.2
    blocks_dropout_rate: 0.1
  decoder:
    hidden_size: 128
    n_att_blocks: 1
    conformer_kernel_size: 9
    n_mel_channels: 80
    att_feature_map_dim: 96
    num_att_heads: 4
    blocks_dropout_rate: 0.1
    postnet_dropout_rate: 0.1
  context_encoder:
    input_emb_dim: 128
    hidden_size: 768
    phonemes_hidden_size: 128
    n_blocks: 1
    cbhg_k_banks: 6
    dropout_rate: 0.1
    num_att_heads: 4
    att_feature_map_dim: 96
  var_adaptor:
    d_model: 128
    multi_speaker: true
    predictor_n_layers: 2
    predictor_n_int_channels: 128
    predictor_kernel_size: 3
    dropout_rate: 0.1
    spk_emb_dim: 512
    use_prosody_modelling: 'utterance'
