run_cfg:
    mlflow_experiment: Default
    mlflow_run_name: Default
    # If true, runs a quick development run (may ignore some settings).
    dev_run: false
    # If set, overrides num_epochs and runs for the specified number of steps.
    continue_training_from_checkpoint: null

train_cfg:
    seed: 2137
    visualize_every_n_epochs: 1
    visualize_n_times_during_training: 5
    val_every_n_epochs: 1
    save_checkpoints: True
    max_epochs: 50
    accumulate_grad_batches: 4
    # If set, loads model weights from the specified checkpoint before training.
    load_model_from_checkpoint: null
    loss_weights:
        mel_loss: 2.0
        pitch_pred_loss: 1.0
        energy_pred_loss: 1.0
        duration_pred_loss: 1.0
    loss_est_max:
        mel_loss: 3.0
        pitch_pred_loss: 1.0
        energy_pred_loss: 1.15
        duration_pred_loss: 40.0
    gradient_clip_val: 0.5
        

data_cfg:
    processed_ds_path: tmp/librittsr_processed
    batch_size: 2
    num_workers: 4
    num_test_samples: 100
    train_val_split: 0.95
    explicit_prosody_quant:
        n_pitch_bins: 48
        pitch_bounds_min: -2.0
        pitch_bounds_max: 3.0
        n_energy_bins: 48
        energy_bounds_min: -2.0
        energy_bounds_max: 3.0

optim_cfg:
    name: adam
    params:
        lr: 0.0002
        betas: [0.9, 0.999]
        eps: 1e-8
    lr_decay: 0.95

model_cfg:
    encoder:
        hidden_size: 384
        phoneme_vocab_size: 74
        pos_tags_vocab_size: 37
        ling_stats_dim: 4
        input_bert_dim: 1536
        n_att_blocks: 6
        conformer_kernel_size: 9
        att_feature_map_dim: 96
        num_att_heads: 4
        prenet_dropout_rate: 0.2
        blocks_dropout_rate: 0.1
    decoder:
        hidden_size: 384
        n_att_blocks: 6
        conformer_kernel_size: 9
        n_mel_channels: 80
        att_feature_map_dim: 96
        num_att_heads: 4
        blocks_dropout_rate: 0.1
        postnet_dropout_rate: 0.1
    context_encoder:
        input_emb_dim: 1536
        hidden_size: 384
        n_blocks: 3
        cbhg_k_banks: 6
        dropout_rate: 0.1
        num_att_heads: 4
        att_feature_map_dim: 96
    var_adaptor:
        d_model: 384
        multi_speaker: True
        predictor_n_layers: 5
        predictor_n_int_channels: 128
        predictor_kernel_size: 3
        dropout_rate: 0.1
        spk_emb_dim: 512